spring:
  jpa:
    show-sql: true # Helpful for development
    hibernate:
      ddl-auto: update

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
